# Created by: Ken Moore <ken@ixsystems.com>
# $FreeBSD$

PORTNAME=	lumina-themes
PORTVERSION=	%%CHGVERSION%%
CATEGORIES=	x11-themes

MAINTAINER=	ken@ixsystems.com
COMMENT=	Lumina desktop wallpapers/colors

LICENSE=	BSD2CLAUSE

USE_QT5=	qmake_build
USES=	qmake

USE_GITHUB=	yes
GH_ACCOUNT=	trueos
GH_PROJECT=	lumina-themes
GH_TAGNAME=	%%GHTAG%%

.include <bsd.port.mk>
