# $FreeBSD$

PORTNAME=	lumina-themes
PORTVERSION=	%%CHGVERSION%%
CATEGORIES=	x11-themes

MAINTAINER=	jt@ixsystems.com
COMMENT=	Lumina desktop wallpapers/colors

LICENSE=	BSD2CLAUSE CC0-1.0

USES=	qmake
USE_QT5=	qmake_build

USE_GITHUB=	yes
GH_ACCOUNT=	trueos
GH_PROJECT=	lumina-themes
GH_TAGNAME=	%%GHTAG%%

.include <bsd.port.mk>
